name: networking
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/network/basic-cdk/
parameters:
  - name: internet-accessible
    value: true
---
name: buckets
path: git::https://github.com/awslabs/seedfarmer-modules.git//modules/storage/buckets/
parameters:
  - name: encryption-type
    value: SSE